# # Login Routes
# # fos_user:
# #     resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# # fos_user_profile:
# #     resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
# #     prefix: /profile

# fos_user_register:
#     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#     prefix: /register

# fos_user_register:
#     resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#     prefix: /register

# fos_user_registration_register:
#     path:     /register
#     defaults: { _controller: FOSUserBundle:Registration:register }

# # fos_user_resetting:
# #     resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
# #     prefix: /resetting

# # fos_user_change_password:
# #     resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
# #     prefix: /profile


fos_user_register:
    resource: "@DeviabLoginBundle/Resources/config/routing.xml"
    prefix: /

fos_user_lender:
    resource: "@DeviabLoginBundle/Controller/LenderController.php"
    prefix: /api/v1/
    type: rest